# Generated by Django 6.0.4 on 2026-04-09 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('ders_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Ders Kodu')),
                ('ders_adi', models.CharField(max_length=100, verbose_name='Ders Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('ogrenci_id', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Öğrenci No')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
            ],
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('sinav_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Sınav ID')),
                ('sinav_adi', models.CharField(max_length=50, verbose_name='Sınav Adı (Vize/Final)')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinavlar', to='okuyucu.ders')),
            ],
        ),
        migrations.CreateModel(
            name='SinavSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_1', models.IntegerField(default=0)),
                ('soru_2', models.IntegerField(default=0)),
                ('soru_3', models.IntegerField(default=0)),
                ('soru_4', models.IntegerField(default=0)),
                ('soru_5', models.IntegerField(default=0)),
                ('toplam_puan', models.IntegerField(default=0)),
                ('ai_karari', models.CharField(max_length=10, verbose_name='Yapay Zeka Kararı')),
                ('okunma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='okuyucu.ogrenci')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogrenci_sonuclari', to='okuyucu.sinav')),
            ],
            options={
                'unique_together': {('ogrenci', 'sinav')},
            },
        ),
    ]
