# Generated by Django 6.0.4 on 2026-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okuyucu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademisyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akademisyen_id', models.CharField(max_length=20, unique=True, verbose_name='Akademisyen ID')),
                ('verdigi_dersler', models.ManyToManyField(blank=True, related_name='akademisyenler', to='okuyucu.ders', verbose_name='Verdiği Dersler')),
            ],
        ),
    ]
