# Generated by Django 6.0.4 on 2026-04-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okuyucu', '0002_akademisyen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinavsonucu',
            name='akademisyen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='okuyucu.akademisyen'),
        ),
    ]
