# Generated by Django 6.0.4 on 2026-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okuyucu', '0003_sinavsonucu_akademisyen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinavsonucu',
            name='soru_1',
        ),
        migrations.RemoveField(
            model_name='sinavsonucu',
            name='soru_2',
        ),
        migrations.RemoveField(
            model_name='sinavsonucu',
            name='soru_3',
        ),
        migrations.RemoveField(
            model_name='sinavsonucu',
            name='soru_4',
        ),
        migrations.RemoveField(
            model_name='sinavsonucu',
            name='soru_5',
        ),
        migrations.AddField(
            model_name='sinavsonucu',
            name='sorular_ve_puanlar',
            field=models.JSONField(default=dict, verbose_name='Sorular ve Puanlar'),
        ),
    ]
