# Generated by Django 6.0.4 on 2026-04-12 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okuyucu', '0004_remove_sinavsonucu_soru_1_remove_sinavsonucu_soru_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akademisyen',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='akademisyen_profili', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sinavsonucu',
            name='onaylandi_mi',
            field=models.BooleanField(default=False, verbose_name='Onaylandı mı?'),
        ),
    ]
