# Generated by Django 6.0.4 on 2026-04-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okuyucu', '0005_akademisyen_user_sinavsonucu_onaylandi_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='kayitli_dersler',
            field=models.ManyToManyField(blank=True, related_name='ogrenciler', to='okuyucu.ders'),
        ),
    ]
